"""seed_platform.py — Adds 7 real Freelancer platform leads (lead_type='platform')"""
import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from app.database import create_tables, save_lead

create_tables()

PLATFORM_LEADS = [
    {
        "company_name":   "Digital Marketing Expert Needed for Real Estate Lead Generation",
        "city":           "Bangalore",
        "category":       "Digital Marketing",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/brand-management/Digital-Marketing-Expert-Needed-for/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 88.0,
        "label":          "HOT",
        "pain_point":     "Client is actively seeking a digital marketing expert for real estate lead gen in East Bangalore — high buying intent.",
        "hot_reason":     "Active project post with budget. Real estate + digital marketing is a high-value niche.",
        "description":    "Platform lead — Freelancer.in project. Industry: Real Estate. Service: Digital Marketing. Location: East Bangalore.",
        "personalized_opener": "I specialize in digital marketing for real estate developers in Bangalore and have driven 200+ qualified leads for similar clients.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Saw your Freelancer project for real estate digital marketing in East Bangalore. We've done this for 5+ developers in the area.",
        "email_subject":  "Proposal: Real Estate Lead Gen — Digital Marketing",
        "email_msg":      "Hi,\n\nI noticed your project on Freelancer for digital marketing for real estate lead generation in East Bangalore.\n\nWe've helped similar developers generate 200+ qualified leads per month using targeted Meta + Google campaigns.\n\nWould love to submit a proposal. Can we connect?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      88, "intent_score": 92, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
    {
        "company_name":   "Automated MetaTrader AI Trading Bot",
        "city":           "Remote",
        "category":       "AI Automation",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/api-developmet/Automated-MetaTrader-Trading-Bot/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 91.0,
        "label":          "HOT",
        "pain_point":     "Client needs AI-powered automated trading bot for MetaTrader — high-value AI automation project.",
        "hot_reason":     "AI + finance automation is a premium niche with high budgets. Active posting.",
        "description":    "Platform lead — Freelancer.in project. Industry: Finance/Trading. Service: AI Automation. Location: Remote.",
        "personalized_opener": "We build production-grade AI trading bots for MetaTrader with backtesting, risk management, and live deployment.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Saw your MetaTrader AI bot project on Freelancer. We've built 3 similar bots for forex traders this year.",
        "email_subject":  "Proposal: Automated MetaTrader AI Trading Bot",
        "email_msg":      "Hi,\n\nYour Freelancer project for an automated MetaTrader AI trading bot caught our attention.\n\nWe build production-grade algorithmic trading systems with backtesting, live deployment, and risk controls.\n\nHappy to share a portfolio. Shall we connect?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      90, "intent_score": 94, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
    {
        "company_name":   "Multi-Service Corporate Website Build",
        "city":           "Remote",
        "category":       "Website Development",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/web-development/Multi-Service-Corporate-Website-Build/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 85.0,
        "label":          "HOT",
        "pain_point":     "Corporate client needs a full multi-service website — active project with clear requirements.",
        "hot_reason":     "Corporate website project with defined scope. Ready-to-hire buyer.",
        "description":    "Platform lead — Freelancer.in project. Industry: Corporate/Business. Service: Website Development. Location: Remote.",
        "personalized_opener": "We build enterprise-grade multi-service corporate websites with CMS, SEO foundation, and modern UI.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Noticed your corporate website project on Freelancer. We specialize in multi-service B2B websites.",
        "email_subject":  "Proposal: Multi-Service Corporate Website",
        "email_msg":      "Hi,\n\nI came across your Freelancer project for a multi-service corporate website.\n\nWe build modern, fast-loading corporate websites with CMS integration, SEO foundation, and responsive design.\n\nWould love to share our portfolio. Can we talk?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      85, "intent_score": 87, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
    {
        "company_name":   "Drama Script Idea Generation",
        "city":           "Remote",
        "category":       "AI Automation",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/creative-writing/Drama-Script-Idea-Generation/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 72.0,
        "label":          "WARM",
        "pain_point":     "Creative writing project — client needs AI-assisted drama script ideation.",
        "hot_reason":     "AI content generation is growing rapidly. Low competition niche on Freelancer.",
        "description":    "Platform lead — Freelancer.in project. Industry: Creative/Media. Service: AI Automation (content generation). Location: Remote.",
        "personalized_opener": "We use AI tools to generate high-quality script concepts, plot outlines, and dialogue frameworks for drama productions.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Saw your drama script project on Freelancer. We combine AI tools with human creativity for script ideation.",
        "email_subject":  "Proposal: Drama Script Idea Generation with AI",
        "email_msg":      "Hi,\n\nYour Freelancer project for drama script idea generation looks interesting.\n\nWe use AI-powered tools combined with creative writing expertise to generate compelling script concepts and story arcs.\n\nInterested in seeing samples?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      70, "intent_score": 74, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
    {
        "company_name":   "Shopify Dropshipping Store Launch",
        "city":           "Remote",
        "category":       "Website Development",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/dropshipping/Shopify-Dropshipping-Store-Launch-40448756/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 83.0,
        "label":          "WARM",
        "pain_point":     "Client launching a Shopify dropshipping store — needs full store setup with product sourcing and design.",
        "hot_reason":     "E-commerce setup projects are quick wins with clear deliverables and repeat potential.",
        "description":    "Platform lead — Freelancer.in project. Industry: E-commerce. Service: Website Development (Shopify). Location: Remote.",
        "personalized_opener": "We've launched 20+ Shopify dropshipping stores with optimized product pages, payment integration, and conversion-focused design.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Saw your Shopify store project on Freelancer. We specialize in dropshipping store launches with high-converting design.",
        "email_subject":  "Proposal: Shopify Dropshipping Store Launch",
        "email_msg":      "Hi,\n\nI came across your Freelancer project for a Shopify dropshipping store.\n\nWe've launched 20+ stores with optimized product listings, payment gateways, and conversion-focused UX.\n\nWant to see our portfolio?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      82, "intent_score": 84, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
    {
        "company_name":   "Restaurant AI Voice Order Agent",
        "city":           "Remote",
        "category":       "AI Automation",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/ai-chatbot/Restaurant-Voice-Order-Agent/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 93.0,
        "label":          "HOT",
        "pain_point":     "Restaurant client wants an AI voice ordering agent — premium AI automation opportunity.",
        "hot_reason":     "AI voice ordering for restaurants is cutting-edge, high-value, and a strong portfolio piece.",
        "description":    "Platform lead — Freelancer.in project. Industry: Restaurants. Service: AI Automation (voice agent). Location: Remote.",
        "personalized_opener": "We build AI voice ordering agents for restaurants using Whisper + LLM stack with POS integration.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Noticed your restaurant AI voice ordering project on Freelancer. This is exactly our specialty.",
        "email_subject":  "Proposal: Restaurant AI Voice Order Agent",
        "email_msg":      "Hi,\n\nYour Freelancer project for a restaurant AI voice order agent is very much in our wheelhouse.\n\nWe build voice ordering systems using Whisper + GPT with POS integration and natural language understanding.\n\nLet us show you a demo?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      93, "intent_score": 96, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
    {
        "company_name":   "Renewable Energy Research Proofreading",
        "city":           "Remote",
        "category":       "Digital Marketing",
        "source":         "Freelancer",
        "source_url":     "https://www.freelancer.in/projects/technical-writing/Renewable-Energy-Research-Proofreading/details",
        "lead_type":      "platform",
        "best_channel":   "Platform Bid",
        "phone":          "",
        "email":          "",
        "website":        "",
        "website_alive":  False,
        "composite_score": 68.0,
        "label":          "COLD",
        "pain_point":     "Client needs technical proofreading for renewable energy research — content services opportunity.",
        "hot_reason":     "Low competition. Good for content/technical writing positioning.",
        "description":    "Platform lead — Freelancer.in project. Industry: Research/Energy. Service: Content & Technical Writing. Location: Remote.",
        "personalized_opener": "We provide technical proofreading and editing for research papers, with experience in energy and sustainability topics.",
        "whatsapp_msg":   "",
        "linkedin_msg":   "Saw your renewable energy proofreading project on Freelancer. We have technical writers with STEM backgrounds.",
        "email_subject":  "Proposal: Renewable Energy Research Proofreading",
        "email_msg":      "Hi,\n\nI noticed your Freelancer project for proofreading a renewable energy research paper.\n\nOur technical writers have backgrounds in engineering and sustainability — we ensure accuracy alongside fluency.\n\nInterested in a sample edit?\n\nBest,\nClientFinder Team",
        "review_status":  "approved",
        "status":         "New",
        "fit_score":      65, "intent_score": 70, "contact_score": 20,
        "pipeline_type":  "intent_pipeline",
    },
]

added = 0
for lead in PLATFORM_LEADS:
    try:
        save_lead(lead)
        added += 1
        print(f"  + {lead['company_name'][:60]}")
    except Exception as e:
        print(f"  ! Skip: {lead['company_name'][:50]} — {e}")

print(f"\nDone: {added} platform leads added.")
