// mockData.js
export const MOCK_LEADS = [
  {
    id: 1,
    company_name: "City General Hospital",
    city: "Mumbai",
    industry: "Healthcare",
    source: "google_maps",
    label: "HOT",
    composite_score: 92,
    fit_score: 95,
    intent_score: 88,
    contact_score: 90,
    pain_point: "Manual patient booking system and slow response times on Google reviews.",
    status: "New",
    rating: 4.2,
    review_count: 850,
    website: "https://example.com/hospital",
    phone: "+91 98765 43210",
    email: "admin@cityhospital.com",
    whatsapp_msg: "Hi Team, I noticed your patient booking system is currently manual. We've helped similar hospitals in Mumbai automate 40% of their operations...",
    linkedin_msg: "Hello, I specialize in AI automation for healthcare...",
    email_subject: "Operational Efficiency for City General",
    email_msg: "Dear Admin, I was reviewing your Google Maps profile...",
    buying_signals: ["Negative reviews about wait times", "High review frequency", "Hiring administrative staff"],
    hot_reason: "High review pain + Active hiring signal detected."
  },
  {
    id: 2,
    company_name: "Apex CA Associates",
    city: "Delhi",
    industry: "Financial Services",
    source: "justdial",
    label: "WARM",
    composite_score: 65,
    fit_score: 70,
    intent_score: 55,
    contact_score: 80,
    pain_point: "Scaling audit workload during tax season without increasing headcount.",
    status: "Contacted",
    rating: 4.8,
    review_count: 120,
    website: "https://example.com/apex-ca",
    phone: "+91 99887 76655",
    email: "contact@apexca.com",
    whatsapp_msg: "Hello Apex Team, managing tax season peak loads can be stressful. Our AI tool...",
    buying_signals: ["Legacy website structure", "Professional directory listing"],
    hot_reason: "Verified professional firm with high reachability."
  },
  {
    id: 3,
    company_name: "Green Valley Resorts",
    city: "Goa",
    industry: "Hospitality",
    source: "sulekha",
    label: "HOT",
    composite_score: 88,
    fit_score: 85,
    intent_score: 92,
    contact_score: 85,
    pain_point: "Losing potential bookings due to 24/7 inquiry handling gaps.",
    status: "New",
    rating: 3.9,
    review_count: 450,
    website: "https://example.com/greenvalley",
    phone: "+91 91234 56789",
    email: "bookings@greenvalley.com",
    whatsapp_msg: "Hi Green Valley! I noticed your resort has a lot of inquiries on social media that go unanswered...",
    buying_signals: ["Inactive social media posts", "Customer complaints about response speed"],
    hot_reason: "Urgent pain in lead response speed detected."
  },
  {
    id: 4,
    company_name: "TechNova Solutions",
    city: "Bangalore",
    industry: "Software",
    source: "clutch",
    label: "COLD",
    composite_score: 35,
    fit_score: 40,
    intent_score: 20,
    contact_score: 60,
    pain_point: "Looking to outsource low-margin maintenance tasks.",
    status: "Dead",
    rating: 4.5,
    review_count: 45,
    website: "https://example.com/technova",
    phone: "+91 88776 65544",
    email: "info@technova.com",
    buying_signals: ["Standard tech profile"],
    hot_reason: "High competition source with low differentiation."
  },
  {
    id: 5,
    company_name: "Prime Estates",
    city: "Pune",
    industry: "Real Estate",
    source: "google_maps",
    label: "WARM",
    composite_score: 72,
    fit_score: 80,
    intent_score: 65,
    contact_score: 85,
    pain_point: "Struggling to follow up with leads from multiple property listing sites.",
    status: "Replied",
    rating: 4.1,
    review_count: 320,
    website: "https://example.com/primeestates",
    phone: "+91 90011 22334",
    email: "sales@primeestates.com",
    whatsapp_msg: "Hi Prime Estates, we can unify all your property leads into one dashboard...",
    buying_signals: ["High volume of active listings", "Slow response time mentioned in reviews"],
    hot_reason: "Clear use case for CRM consolidation."
  },
  {
    id: 6,
    company_name: "The Spice Route",
    city: "Hyderabad",
    industry: "Restaurant",
    source: "zomato",
    label: "HOT",
    composite_score: 85,
    fit_score: 90,
    intent_score: 80,
    contact_score: 75,
    pain_point: "High delivery platform commissions eating into margins.",
    status: "Meeting",
    rating: 4.4,
    review_count: 1200,
    website: "https://example.com/spiceroute",
    phone: "+91 99000 11111",
    email: "manager@spiceroute.com",
    whatsapp_msg: "Hi Manager, we help restaurants build their own direct ordering systems to save 20% on commissions...",
    buying_signals: ["Active on delivery apps", "Complaints about delivery fees from customers"],
    hot_reason: "High transaction volume makes commission saving very attractive."
  },
  {
    id: 7,
    company_name: "Swift Logistics",
    city: "Chennai",
    industry: "Logistics",
    source: "justdial",
    label: "COLD",
    composite_score: 45,
    fit_score: 50,
    intent_score: 40,
    contact_score: 55,
    pain_point: "Manual route planning causing fuel inefficiencies.",
    status: "New",
    rating: 3.5,
    review_count: 85,
    website: "https://example.com/swiftlogistics",
    phone: "+91 88888 77777",
    email: "ops@swiftlogistics.com",
    whatsapp_msg: "Hello Swift Logistics, our AI route optimization can reduce fuel costs by 15%...",
    buying_signals: ["Expanding fleet size indicated on website"],
    hot_reason: "Niche industry, requires longer sales cycle."
  },
  {
    id: 8,
    company_name: "Bright Minds Academy",
    city: "Ahmedabad",
    industry: "Education",
    source: "google_maps",
    label: "HOT",
    composite_score: 89,
    fit_score: 92,
    intent_score: 85,
    contact_score: 95,
    pain_point: "Overwhelmed with admissions inquiries during peak season.",
    status: "Contacted",
    rating: 4.7,
    review_count: 540,
    website: "https://example.com/brightminds",
    phone: "+91 77777 66666",
    email: "admissions@brightminds.edu",
    whatsapp_msg: "Hi Bright Minds, an AI chatbot can handle 80% of routine admission inquiries instantly...",
    buying_signals: ["Admission season approaching", "High website traffic"],
    hot_reason: "Immediate seasonal need for automation."
  },
  {
    id: 9,
    company_name: "Glow Spa & Salon",
    city: "Kolkata",
    industry: "Wellness",
    source: "sulekha",
    label: "WARM",
    composite_score: 68,
    fit_score: 75,
    intent_score: 60,
    contact_score: 80,
    pain_point: "No show appointments and manual reminders.",
    status: "New",
    rating: 4.6,
    review_count: 210,
    website: "https://example.com/glowspa",
    phone: "+91 66666 55555",
    email: "hello@glowspa.com",
    whatsapp_msg: "Hi Glow Spa, automated WhatsApp reminders can reduce no-shows by 40%...",
    buying_signals: ["Online booking link is broken", "Active Instagram presence"],
    hot_reason: "Easy tech fix with immediate ROI."
  },
  {
    id: 10,
    company_name: "Steel Forge India",
    city: "Ludhiana",
    industry: "Manufacturing",
    source: "indiamart",
    label: "COLD",
    composite_score: 40,
    fit_score: 45,
    intent_score: 30,
    contact_score: 50,
    pain_point: "Outdated inventory management using spreadsheets.",
    status: "New",
    rating: 4.0,
    review_count: 55,
    website: "https://example.com/steelforge",
    phone: "+91 55555 44444",
    email: "info@steelforge.in",
    whatsapp_msg: "Hello Steel Forge, upgrading from spreadsheets to a cloud inventory system is easier than you think...",
    buying_signals: ["Recent Indiamart verified badge"],
    hot_reason: "Traditional industry, slow tech adoption."
  }
];

export const MOCK_STATS = {
  total_leads: 1240,
  hot_leads: 85,
  warm_leads: 310,
  cold_leads: 845,
  conversion_rate: 12.4,
  revenue_projection: "₹12.5L",
  daily_trend: [12, 45, 32, 67, 89, 43, 55]
};

export const MOCK_JOB = {
  id: "job_mock_123",
  status: "done",
  stage: "Saving Results",
  message: "10 leads successfully processed and saved.",
  progress: 100,
  result: {
    total_leads: 10,
    hot_leads: [MOCK_LEADS[0], MOCK_LEADS[2], MOCK_LEADS[5], MOCK_LEADS[7]],
    warm_leads: [MOCK_LEADS[1], MOCK_LEADS[4], MOCK_LEADS[8]],
  }
};
