// mockData.js
export const MOCK_LEADS = [
  {
    id: 1,
    company_name: "City General Hospital",
    city: "Mumbai",
    industry: "Healthcare",
    source: "google_maps",
    label: "HOT",
    composite_score: 92,
    fit_score: 95,
    intent_score: 88,
    contact_score: 90,
    pain_point: "Manual patient booking system and slow response times on Google reviews.",
    status: "New",
    rating: 4.2,
    review_count: 850,
    website: "https://example.com/hospital",
    phone: "+91 98765 43210",
    email: "admin@cityhospital.com",
    whatsapp_msg: "Hi Team, I noticed your patient booking system is currently manual. We've helped similar hospitals in Mumbai automate 40% of their operations...",
    linkedin_msg: "Hello, I specialize in AI automation for healthcare...",
    email_subject: "Operational Efficiency for City General",
    email_msg: "Dear Admin, I was reviewing your Google Maps profile...",
    buying_signals: ["Negative reviews about wait times", "High review frequency", "Hiring administrative staff"],
    hot_reason: "High review pain + Active hiring signal detected."
  },
  {
    id: 2,
    company_name: "Apex CA Associates",
    city: "Delhi",
    industry: "Financial Services",
    source: "justdial",
    label: "WARM",
    composite_score: 65,
    fit_score: 70,
    intent_score: 55,
    contact_score: 80,
    pain_point: "Scaling audit workload during tax season without increasing headcount.",
    status: "Contacted",
    rating: 4.8,
    review_count: 120,
    website: "https://example.com/apex-ca",
    phone: "+91 99887 76655",
    email: "contact@apexca.com",
    whatsapp_msg: "Hello Apex Team, managing tax season peak loads can be stressful. Our AI tool...",
    buying_signals: ["Legacy website structure", "Professional directory listing"],
    hot_reason: "Verified professional firm with high reachability."
  },
  {
    id: 3,
    company_name: "Green Valley Resorts",
    city: "Goa",
    industry: "Hospitality",
    source: "sulekha",
    label: "HOT",
    composite_score: 88,
    fit_score: 85,
    intent_score: 92,
    contact_score: 85,
    pain_point: "Losing potential bookings due to 24/7 inquiry handling gaps.",
    status: "New",
    rating: 3.9,
    review_count: 450,
    website: "https://example.com/greenvalley",
    phone: "+91 91234 56789",
    email: "bookings@greenvalley.com",
    whatsapp_msg: "Hi Green Valley! I noticed your resort has a lot of inquiries on social media that go unanswered...",
    buying_signals: ["Inactive social media posts", "Customer complaints about response speed"],
    hot_reason: "Urgent pain in lead response speed detected."
  },
  {
    id: 4,
    company_name: "TechNova Solutions",
    city: "Bangalore",
    industry: "Software",
    source: "clutch",
    label: "COLD",
    composite_score: 35,
    fit_score: 40,
    intent_score: 20,
    contact_score: 60,
    pain_point: "Looking to outsource low-margin maintenance tasks.",
    status: "Dead",
    rating: 4.5,
    review_count: 45,
    website: "https://example.com/technova",
    phone: "+91 88776 65544",
    email: "info@technova.com",
    buying_signals: ["Standard tech profile"],
    hot_reason: "High competition source with low differentiation."
  }
];

export const MOCK_STATS = {
  total_leads: 1240,
  hot_leads: 85,
  warm_leads: 310,
  cold_leads: 845,
  conversion_rate: 12.4,
  revenue_projection: "₹12.5L",
  daily_trend: [12, 45, 32, 67, 89, 43, 55]
};

export const MOCK_JOB = {
  id: "job_mock_123",
  status: "done",
  stage: "Saving Results",
  message: "15 leads successfully processed and saved.",
  progress: 100,
  result: {
    total_leads: 15,
    hot_leads: [MOCK_LEADS[0], MOCK_LEADS[2]],
    warm_leads: [MOCK_LEADS[1]],
  }
};
